### ISSUE TITLE
C:\fakepath

### ISSUE THREAD

**Issue by MrMuttons** [nokonoko/Uguu#40] opened 2018-01-19 20:31 UTC
So, I'm not really sure what's causing this, as I'm new to html, and wanted a simple file / image host for a few friends, i followed the instructions to the best of my knowledge, yet i get C:\fakepath\image.png when i select it from chrome, and when i upload it, it takes me to Site/api.php?d=upload with an error 500

**Comment by nokonoko** [comment] 2018-01-20 02:58
Are you uploading with a phone?

Skickat från min iPhone

**Comment by MrMuttons** [comment] 2018-01-20 17:02
No. uploading it to my raspberry pi via sftp from windows

**Comment by nokonoko** [comment] 2018-01-20 17:14
Are u usimg the correct post request? What are u trying to do, why via sftp???

Skickat från min iPhone

**Comment by Jeroen52** [comment] 2018-01-20 18:41
@nokonoko Could be that he meant that he uploaded the uguu code via SFTP instead of using `git clone`.

Does the webserver have the rights to access the files? Are they under the correct owner?

Use `ls -lah` to check the permissions of the files.

You can use `chown -R apache:apache /path/to/uguu` to set the user to that of your webserver, of course replacing `apache` with the correct user.

Try to set the permissions of the directory recursively to 770.
```bash
chmod -R 770 /your/path/to/uguu
```

**Comment by MrMuttons** [comment] 2018-01-20 21:05
i'm not sure about the owner bit. 
but when i did the chmod, the site throws a 403

again, 0 clue as to what im actually doing. i mostly copy + paste with no real knowledge of what im doing

**Comment by Jeroen52** [comment] 2018-01-20 22:52
Error 403 means forbidden, so the file is most likely inaccessible for the webserver from the filesystem.

Can you paste your `ls -lah`?

**Comment by MrMuttons** [comment] 2018-01-21 00:27
i got it working now, but i still get  
https://gyazo.com/4819bcd9f65173249ac6be94b3354262

**Comment by Jeroen52** [comment] 2018-01-21 00:30
And you installed uguu on a Raspberry Pi?

**Comment by MrMuttons** [comment] 2018-01-21 00:35
yes

**Comment by Jeroen52** [comment] 2018-01-21 00:48
Can you execute `php -v`?

**Comment by MrMuttons** [comment] 2018-01-21 00:52
PHP 7.0.19-1 (cli) (built: May 11 2017 14:04:47) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.19-1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by Jeroen52** [comment] 2018-01-21 01:01
Does the file actually get uploaded to the server? Is it only the redirect that doesn't work?

If that isn't the case, can you make a video of you uploading a file or try to use `tail -f` on the error_log file.

**Comment by MrMuttons** [comment] 2018-01-21 01:03
the file doesnt even upload. it throws something about an api in the address bar, but doesnt work

**Comment by MrMuttons** [comment] 2018-01-21 01:09
https://youtu.be/k0IoaHK477M
and i see no error_log. do you mean error.php, or error_meow.php

**Comment by Jeroen52** [comment] 2018-01-21 01:22
`error_log` should be somewhere in `/var/log/apache` or `/var/log/httpd`, please show the contents of those directories using `ls -l`

**Comment by MrMuttons** [comment] 2018-01-21 01:26
total 156
-rw-r--r-- 1 www-data www-data      0 Dec 24 06:25 access.log
-rw-r--r-- 1 www-data www-data 123769 Dec 16 23:06 access.log.1
-rw-r--r-- 1 www-data www-data  10091 Jan 21 01:06 error.log
-rw-r--r-- 1 www-data www-data    316 Jan 12 22:35 error.log.1
-rw-r--r-- 1 www-data www-data    143 Jan  7 01:27 error.log.2.gz
-rw-r--r-- 1 www-data www-data    187 Dec 28 04:24 error.log.3.gz
-rw-r--r-- 1 www-data www-data    675 Dec 24 00:03 error.log.4.gz

**Comment by MrMuttons** [comment] 2018-01-21 01:28
side note, how would i get a folder to look like this? 
https://gyazo.com/e20709bab112161ccc610faa9dbde6de

**Comment by Jeroen52** [comment] 2018-01-21 01:34
That'd be a bit more difficult, as it seems that you're not using a separate virtualhost. If you were to place a .htaccess in ./public/files then it could be deleted again.

First of all, what kind of errors are there in error.log?

**Comment by MrMuttons** [comment] 2018-01-21 01:38
https://paste.ubuntu.com/26427112/
heres everything in it

**Comment by Jeroen52** [comment] 2018-01-21 01:42
What is the contents of your `/var/www/html/includes/config.php`?

**Comment by MrMuttons** [comment] 2018-01-21 01:45
https://paste.ubuntu.com/26427142/

**Comment by MrMuttons** [comment] 2018-01-21 01:50
it uploads, but still says fakepath in it.

**Comment by Jeroen52** [comment] 2018-01-21 01:55
The fakepath issue doesn't seem like anything important.

But you could do the following and paste the output.

`grep -r 'fakepath' /var/www/html/`

**Comment by MrMuttons** [comment] 2018-01-21 01:56
there was no output
https://gyazo.com/a96b15b4a7ec9121ba15030a2c26aa91

**Comment by Jeroen52** [comment] 2018-01-21 02:03
I just searched something, and I realized what the problem was.

There is no problem, it is a security feature.

https://stackoverflow.com/questions/4851595/how-to-resolve-the-c-fakepath

**Comment by MrMuttons** [comment] 2018-01-21 02:04
heck. well then. thanks for all the help by the way.

**Comment by MrMuttons** [comment] 2018-01-21 02:05
Wait, im still having the issue above, 
when clicking the link it gives, it takes me to files/filename.png
instead of /public/files/filename.png

**Comment by Jeroen52** [comment] 2018-01-21 02:07
Do you get a 404 error when clicking on that link?

**Comment by MrMuttons** [comment] 2018-01-21 02:07
yep

**Comment by Jeroen52** [comment] 2018-01-21 02:09
A "yep" on the 404 or a "yep" that the file exists when you manually go to it?

**Comment by MrMuttons** [comment] 2018-01-21 02:10
yep for both

**Comment by Jeroen52** [comment] 2018-01-21 02:28
I'm going to sleep right now, but it might be something to do that the webserver config isn't done properly, and in specific allowing override in the directory.

https://github.com/nokonoko/Uguu/blob/master/README.md

If I have time tomorrow morning I could help you through it, if not I'm sure that @nokonoko can help you from here.

**Comment by MrMuttons** [comment] 2018-01-21 02:29
least it works now. Thanks for all the help!

**Comment by Jeroen52** [comment] 2018-01-21 02:31
No problem, it isn't set up 100% properly it seems.

Are you sure you followed the installation guide properly and didn't skip anything?

**Comment by MrMuttons** [comment] 2018-01-21 02:37
im not sure. i don't think i did the virtual host.
after reading that bit, i saw this. and think it may be an issue. but im using neither nginx nor apache
 Alias "/files" "/var/www/Uguu/public/files/"
        <Directory /var/www/Uguu/public/files/>

**Comment by MrMuttons** [comment] 2018-01-21 02:39
not even sure how to set up virtualhost.

**Comment by MrMuttons** [comment] 2018-01-21 20:28
I've fixed the eorr with the uploaded file being pointed to /files/ instead of /public/files/
was missing /public/ in upload-done.php

Thanks for all the help @Jeroen52

**Comment by Jeroen52** [comment] 2018-01-21 22:05
That is really weird, it should work out of the box if you edit only the config files.

**Comment by Jeroen52** [comment] 2018-01-22 01:06
Did you set up a crontab?

**Comment by MrMuttons** [comment] 2018-01-22 03:29
i don't believe so

**Comment by MrMuttons** [comment] 2018-01-22 03:32
got it

**Comment by MrMuttons** [comment] 2018-01-27 23:44
im not sure i saw the way to change the file size limit. i'd like it to be 300mb, but i didnt really see it in the documentation, nor the configs?

**Comment by Jeroen52** [comment] 2018-01-28 01:02
The file size limit is PHP's file size limit, so edit /etc/php.ini

**Comment by Jeroen52** [comment] 2018-02-09 19:45
Can we close this issue?

**Closed** 2018-02-09 21:42 UTC

**Comment by cicina** [comment] 2018-09-24 21:36
Hello, I can confirm, the path of the uploaded file is indeed wrong in upload-done.php. Not a big deal though. Just installed your software, it works nicely thanks!

**Comment by NyanKiyoshi** [comment] 2018-09-25 13:15
It's just a feature from some browsers to prevent JavaScript from knowing your file's local full path.
